### ISSUE TITLE
3 major fixes needed with activeDev

### ISSUE THREAD

**Issue by kopardev** [CCBR/CHARLIE#64]
- DCC error again...
```
+ DCC @/vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/LEC_24hpi_R1/DCC/samplesheet.txt --temp /lscratch/62408434/ca01d743-6c80-4ee4-ba0b-e4e9105be323/DCC --threads 4 --detect --gene --bam /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/LEC_24hpi_R1/STAR2p/LEC_24hpi_R1_p2.bam -ss --annotation /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/ref/ref.fixed.gtf --chrM -G --rep_file /data/Ziegelbauer_lab/resources/fastas_gtfs/hg38.repeats.gtf --refseq /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/ref/ref.fa --PE-independent -mt1 @/vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/LEC_24hpi_R1/DCC/mate1.txt -mt2 @/vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/LEC_24hpi_R1/DCC/mate2.txt
[W::hts_idx_load3] The index file is older than the data file: /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/LEC_24hpi_R1/STAR2p/LEC_24hpi_R1_p2.bam.csi
Traceback (most recent call last):
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/DCC/bin/DCC", line 11, in <module>
    load_entry_point('DCC==0.5.0', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 492, in main
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 680, in findCircSkipJunction
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 281, in findcircAdjacent
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 222, in getAdjacent
ValueError: invalid literal for int() with base 10: '127997-129368_transcript_1'
[Sat Apr  8 08:43:42 2023]
Error in rule dcc:
```
 this is probably due to the the `:` in the `transcript_id` .

 Solution: Replace the `:` with `_`.

- ciri error while creating CRAM file
```
+ perl /data/Ziegelbauer_lab/tools/CIRI_v2.0.6/CIRI2.pl -I iSLK_BAC16_72hpi_R2.bwa.sam -O /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/iSLK_BAC16_72hpi_R2/ciri/iSLK_BAC16_72hpi_R2.ciri.out -F /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/ref/ref.fa -A /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/ref/ref.fixed.gtf -G /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/iSLK_BAC16_72hpi_R2/ciri/iSLK_BAC16_72hpi_R2.ciri.log -T 56
+ samtools view -@56 -T /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/ref/ref.fa -CS iSLK_BAC16_72hpi_R2.bwa.sam
+ samtools sort -l 9 -T /lscratch/62403479/cecea650-f0e6-4cb5-8db5-2c3aac3a6c8b --write-index -@56 -O CRAM -o /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/iSLK_BAC16_72hpi_R2/ciri/iSLK_BAC16_72hpi_R2.ciri.cram -
[bam_sort_core] merging from 0 files and 56 in-memory blocks...
[E::cram_populate_ref] Mismatching md5sum for downloaded reference
[E::cram_get_ref] Failed to populate reference for id 0
[W::cram_encode_container] Failed to load reference #0
[W::cram_encode_container] Enabling embed_ref=2 mode to auto-generate reference
[W::cram_encode_container] NOTE: the CRAM file will be bigger than using an external reference
/usr/bin/bash: line 28: 143027 Done                    samtools view -@56 -T /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/ref/ref.fa -CS iSLK_BAC16_72hpi_R2.bwa.sam
     143028 Segmentation fault      | samtools sort -l 9 -T $TMPDIR --write-index -@56 -O CRAM -o /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_230408/results/iSLK_BAC16_72hpi_R2/ciri/iSLK_BAC16_72hpi_R2.ciri.cram -
[Sat Apr  8 04:28:36 2023]
Error in rule ciri:
```

Solution: Abandoning CRAM format and sticking with BAM

 - Argument list too long
 ```
/vf/users/Ziegelbauer_lab/Pipelines/circRNA/230406_activeDev_20284a3/workflow/scripts/_create_circExplorer_linear_bam.sh: line 214: /usr/bin/rm: Argument list too long
[Sat Apr  8 06:55:13 2023]
Error in rule create_circExplorer_linear_spliced_bams:
```
Solution: delete the whole folder!

**Comment by kopardev** [comment]
Done!
